CREATE TABLE CUSTOMER(
ID integer  NOT NULL,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CREATED_DATE DATE NOT NULL,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID));

INSERT INTO CUSTOMER (ID, NAME, EMAIL, CREATED_DATE) VALUES(1, 'Asish','***@yahoo.com', TO_DATE('2017-10-08', 'yyyy-mm-dd'));
INSERT INTO CUSTOMER (ID, NAME, EMAIL, CREATED_DATE) VALUES(2, 'Titu','@@@@gmail.com', TO_DATE('2017-10-08', 'yyyy-mm-dd'));
INSERT INTO CUSTOMER (ID, NAME, EMAIL, CREATED_DATE) VALUES(3, 'Aryan','&&&@yahoo.com', TO_DATE('2017-10-08', 'yyyy-mm-dd'));


select * from customer